---
- name: Server monitoring
  hosts: localhost
  gatther_facts: true
  connection: local

  collections: 
   - amazon.aws

  vars:
    aws_region: us-east-1
    instance_name: server creation
    instance_type: t3.micro
    ami_id: ami-XXXXXXX
    key_name: key #ex-ssh
    subnet_id: subnet-XXXXXXXXXX
    security_group: sg-xxxxxxxx
    volume_size:30 #storage, Gb
    environment: Dev

  tasks:
    - name: Launch ec2 instance
      amazon.aws.ec2_instance:
      region: "{{ aws_region }}"
      instance_name: "{{instance_name}}"
      image_id: "{{ami_id}}"
      instance_type: "{{ instance_type }}"
      key_name: "{{key_name}}"
      subnet_id: "{{subnet_id}}"
      wait: true
      state: running
    
    - name: Calculate expiry date
      set_fact:
        expire_date: >- {{ '%Y-%m-%d' | strftime((ansible_date_time.epoch | int) + (30 * 24 * 60 * 60)) }} 
    - name: check for instancce existance
      fail:
        msg: " Ec2 instance {{instance_ids}} is not found"
      when: length==0 | ec2_info.instance_ids

    - name: collecting tags details
      amazon.aws.ec2_tag:
        region: "{{ aws_region }}"
        resource: "{{ instance_id }}"
        tags:
          CreationDate: "{{ ansible_date_time.date }}"
          ExpiryDate: "{{ expire_date }}"
          Lifespan: "30Days"
          ManagedBy: "AAP"
          Owner: "{{ owner | default('Unknown') }}"
      register: ec2_tags

    - name: Display reslt 
      debug:
        var:
          - ec2.tags
